server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: academic-portal-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/academic_portal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: home@f04
  
  # H2 console disabled for MySQL
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations:
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLongForSecurity
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000,http://localhost:3002
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.academicportal: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
